#!/usr/pkg/bin/bash

echo "Content-type: text/html; Charset=UTF-8;"
echo ""
echo "<!DOCTYPE html>"
echo "<html lang='en'>"
echo "<head>"
echo "    <meta charset='UTF-8'>"
echo "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>"
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
echo "    <title>Document</title>"
echo "    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>"
echo "    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
echo "    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>"
echo "    <style>"
echo "        /* Sidebar */"
echo "#sidebar-wrapper{"
echo "  z-index:1;"
echo "  position: absolute;"
echo "  width:0;"
echo "  height:100%;"
echo "  overflow-y:hidden;"
echo "  background: #5b4282;"
echo "  opacity:0.9;"
echo "	transition:all .5s;"
echo "	display:flex;"
echo "	align-items:center;"
echo "}"
echo ""
echo "/* Main Content */"
echo "#page-content-wrapper{"
echo "  width: 100%;	"
echo "  position: absolute;"
echo "  padding:15px;"
echo "	transition:all .5s;"
echo "}"
echo ""
echo "#menu-toggle{"
echo "	transition:all .3s;"
echo "	font-size:2em;"
echo "}"
echo "/* Change the width of the sidebar to display it*/"
echo "#wrapper.menuDisplayed #sidebar-wrapper{"
echo "  width:250px;"
echo "}"
echo ""
echo "#wrapper.menuDisplayed #page-content-wrapper{"
echo "  padding-left:250px;"
echo "}"
echo ""
echo "/* Sidebar styling */"
echo ".sidebar-nav{"
echo "  padding:0;"
echo "  list-style:none; "
echo "	transition:all .5s;"
echo "	width:100%;"
echo "	text-align:center;"
echo "}"
echo ""
echo ".sidebar-nav li{"
echo "  line-height:40px;  "
echo "	width:100%;"
echo "	transition:all .3s;"
echo "	padding:10px;"
echo "}"
echo ""
echo ".sidebar-nav li a {"
echo "  display:block;"
echo "  text-decoration:none;"
echo "  color:#ddd;"
echo "}"
echo ""
echo ".sidebar-nav li:hover{"
echo "  background:#846bab;"
echo "}"
echo ""
echo ".responsive-iframe {"
echo "  position: absolute;"
echo "  top: 0;"
echo "  left: 10px;"
echo "  bottom: 0;"
echo "  right: 0;"
echo "  width: 75%;"
echo "  height: 100%;"
echo "  border: none;"
echo "}"
echo ""
echo ".container {"
echo "position: relative;"
echo "  width: 100%;"
echo "  overflow: hidden;"
echo " padding-top: 100%; "
echo "}"
echo ""
echo ""
echo "    </style>"
echo "</head>"
echo "<body>"
echo "    "
echo "    <body>"
echo "        <div id='wrapper'>"
echo "          <div id='sidebar-wrapper'>"
echo "            <ul class='sidebar-nav'>"
echo "              <li><a href='/cgi-bin/parcial4/ifconfig.cgi'>ifconfig</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/neofetch.cgi'>neofetch</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/w.cgi'>w</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/gateway.cgi'>gateway</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/resolv.cgi'>resolv</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/df.cgi'>df</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/hostname.cgi'>hostname</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/kernel.cgi'>kernel</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/os.cgi'>Sistema operativo</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/nmap.cgi'>nmap</a></li>"
echo "              <li><a href='/cgi-bin/parcial4/ps.cgi'>ps</a></li>"
echo "            </ul>"
echo "          </div>"
echo "          "
echo "          <div id='page-content-wrapper'>"
echo "            <div class='container-fluid'>"
echo "              <div class='row'>"
echo "                <div class='col-lg-12'>"
echo "                  <a href='#' class='btn' id='menu-toggle'><span class='glyphicon glyphicon-menu-hamburger'></span></a>"
echo "                  <h1 class='text-center'>Juan Diego Reyes Zepeda</h1>"
echo "                  <h2 class='text-center'>5190-18-5233</h2>"
echo "                  <h3>Comando: ps \$\$</h3>"
echo "                  <h3>Sistema operativo $(uname) $(uname -r)</h3>"
echo "                  <pre>"
echo "                    $(ps $$)"
echo "                  </pre>"
echo "                </div>"
echo "              </div>"
echo "            </div>"
echo "          </div>"
echo "        </div>"
echo "          "
echo "          "
echo "        <script src='https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js' integrity='sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj' crossorigin='anonymous'></script>"
echo "        <script src='https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js' integrity='sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct' crossorigin='anonymous'></script>"
echo "            <script "
echo "            type='text/javascript' "
echo "            language='JavaScript'>"
echo ""
echo ""
echo ""
echo "            \$(document).ready(function(){"
echo "            \$('#menu-toggle').click(function(e){"
echo "                e.preventDefault();"
echo "                \$('#wrapper').toggleClass('menuDisplayed');"
echo "            });"
echo "            });"
echo ""
echo "        </script>"
echo "    </body>"
echo "</body>"
echo "</html>"
